version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-battle-city-ai
    webide-port: 6800
    
    ports: # 申明端口
      tools-webide-vscode: 6800
      tools-ssh: 6822
      apps-battle-city-ai: 8080
    
    ide-type: vscode  #vscode/theia
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config set registry https://registry.npmmirror.com
      - npm install
      - git init && git add . && git commit -m "SmartIDE init"
      - npm start
  services:
    smartide-battle-city-ai:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-base:latest
      restart: always
      environment:
        ROOT_PASSWORD: root123
        LOCAL_USER_PASSWORD: root123       
      volumes:
      - .:/home/project/
      expose:
        - 3000
        - 8080
      ports:
        - 6800:3000
        - 6822:22
        - 8080:8080
      networks:
        - smartide-network

  networks:
    smartide-network:
      external: true