
version: "3"
services:
  smartide-node-dev:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-node-v2:latest
    imagePullPolicy: Always
    restart: always
    environment:
      LOCAL_USER_PASSWORD: root123       
    volumes:
    - .:/home/project
    ports:
      - 6822:22
    networks:
      - smartide-network

networks:
  smartide-network:
    external: true