---

apiVersion: v1
kind: Pod
metadata:
  name: smartide-vmlc-vscode-cpp-dev
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
  labels:
    smartide-cpp-vmlc.service: smartide-cpp-vmlc
spec:
  runtimeClassName: sysbox-runc
  containers:
    - env:
        - name: LOCAL_USER_PASSWORD
          value: root123     
      name: smartide-vmlc-vscode-cpp-dev
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-cpp-v2-vscode-vmlc:latest
      command: ["/sbin/init"]
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
        - containerPort: 22

---

apiVersion: v1
kind: Service
metadata:
  name: smartide-vmlc-vscode-cpp-service
spec:
  ports:   
    - name: "6800"
      port: 6800
      targetPort: 3000 
    - name: "6822"
      port: 6822
      targetPort: 22
  selector:
    smartide-cpp-vmlc.service: smartide-cpp-vmlc
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smartide-cpp-vmlc-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              smartide-cpp-vmlc/smartide-network: "true"
  podSelector:
    matchLabels:
      smartide-cpp-vmlc/smartide-network: "true"