version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-hugo-dev
    ports:
      tools-webide-port: 6800
      tools-ssh: 6822
      apps-hugo-dev-site: 1313
      apps-nginx-prod-site: 8080
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
    command:
      # 初始化完成后请删除以下脚本，git init && git submodule只需要执行一次
      - git init && git submodule add https://gitee.com/smartide/docsy.git themes/docsy
      - git submodule update --init --recursive
      - npm config set registry https://registry.npmmirror.com
      - npm install
      # 初始化完成后请删除以下2行脚本，后续请通过手工方式提交代码
      - git add . && git commit -m "SmartIDE init"
      - hugo server --bind 0.0.0.0 --disableFastRender --forceSyncStatic --buildDrafts --buildFuture 
      
  services:
    smartide-hugo-dev:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-hugo:latest
      restart: always
      environment:
        ROOT_PASSWORD: root123
      volumes:
        - .:/home/project
      expose:
        - 1313
      ports:
        - 6822:22
        - 6800:3000
        - 1313:1313
      networks:
        - smartide-network 

    web:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/nginx:stable-alpine-perl
      restart: always
      volumes:
        - './.ide/.temp/nginx/html:/usr/share/nginx/html'
        - './.ide/.temp/nginx/logs:/var/log/nginx'
        - './.ide/nginx/conf.d:/etc/nginx/conf.d'
        - './.ide/nginx/nginx.conf:/etc/nginx/nginx.conf'
      ports:
        - 8080:80
      expose:
        - 8080
      networks:
        - smartide-network  

  networks:
    smartide-network:
      external: true