
---

apiVersion: v1
kind: Pod
metadata:
  name: smartide-cpp-vmlc-dev
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
  labels:
    smartide-cpp.service: smartide-cpp
spec:
  runtimeClassName: sysbox-runc
  containers:
    - env:
        - name: LOCAL_USER_PASSWORD
          value: root123     
      name: smartide-cpp-vmlc-dev
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-cpp-v2-vmlc:latest
      command: ["/sbin/init"]
      imagePullPolicy: Always
      ports:
        - containerPort: 22

---

apiVersion: v1
kind: Service
metadata:
  name: smartide-cpp-vmlc-service
spec:
  ports:    
    - name: "6822"
      port: 6822
      targetPort: 22
  selector:
    smartide-cpp.service: smartide-cpp
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smartide-cpp-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              smartide-cpp/smartide-network: "true"
  podSelector:
    matchLabels:
      smartide-cpp/smartide-network: "true"
