version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-python
    ports:
      webide: 6800
      ssh: 6822
      application: 3001
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
      
  services:
    smartide-template-python:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-python-v2:2104
      restart: always
      environment:
        LOCAL_USER_PASSWORD: root123
      volumes:
        - .:/home/project
      ports:
        - 3001:3001
        - 6822:22
        - 6800:3000
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true