version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-python
    ports:
      tools-ssh: 6822
    ide-type: sdk-only
    volumes: 
      git-config: true
      ssh-key: true
      
  services:
    smartide-template-python:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-python-v2:2197
      restart: always
      environment:
        LOCAL_USER_PASSWORD: root123
      volumes:
        - .:/home/project
      ports:
        - 6822:22
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true