version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-base
    ports:
      webide: 6800
      ssh: 6822
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
  services:
    smartide-template-base:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-base
      restart: always
      environment:
        LOCAL_USER_ID: id -u $USER
        LOCAL_USER_GID: id -g $USER
        LOCAL_PASSWORD: root123
      volumes:
        - .:/home/project
      expose:
        - 3000
      ports:
        - 3001:3001
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true