version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-java-vscode
    ports:
      tools-webide-port: 6800
      tools-ssh: 6822
      apps-application: 3001
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - code --install-extension vscjava.vscode-java-pack
      - code --install-extension pivotal.vscode-boot-dev-pack
  services:
    smartide-template-java-vscode:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-java-v2-vscode:2192
      restart: always
      environment:
        ROOT_PASSWORD: root123
        LOCAL_USER_PASSWORD: root123
      ports:
        - 6822:22
        - 6800:3000
        - 3001:3001
      volumes:
        - .:/home/project
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true      
