version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: smartide-golang-vmlc-go-dev

    ports:
      tools-webide-goland: 6800
      tools-ssh: 6822
    ide-type: jb-projector

    volumes: 
      git-config: true
      ssh-key: true
    command:
      - go env -w GOPROXY=https://goproxy.cn,direct

  kube-deploy-files: "golang-vmlc-k8s-deployment.yaml" 
  docker-compose-file: "golang-vmlc-docker-compose.yaml"