version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-cpp
    ports:
      tools-ssh: 6822
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
  services:
    smartide-template-cpp:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-cpp-v2:2156
      restart: always
      environment:
        ROOT_PASSWORD: root123
        LOCAL_USER_PASSWORD: root123
      ports:
        - 6822:22
      volumes:
        - .:/home/project
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true      
