version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: smartide-idea-vmlc-java-dev

    ports:
      tools-webide-idea: 6800
      tools-ssh: 6822
    ide-type: jb-projector

    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config get registry

  kube-deploy-files: "idea-vmlc-k8s-deployment.yaml" 
  docker-compose-file: "idea-vmlc-docker-compose.yaml"