version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-node-vscode
    ports:
      tools-webide-vscode: 6800
      tools-ssh: 6822
      apps-application: 3001
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
      
  services:
    smartide-template-node-vscode:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-base-v2-vscode:1748
      restart: always
      environment:
        LOCAL_USER_PASSWORD: root123
      volumes:
        - .:/home/project
      ports:
        - 6822:22
        - 6800:3000
        - 3001:3001
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true