version: smartide/v0.1
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-java
    ports:
      webide: 6800
      ssh: 6822
    ide-type: vscode
    volumes: 
        git-config: true
        ssh-key: true
  services:
    smartide-template-java:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-java-opvscode:latest
      restart: always
      environment:
        ROOT_PASSWORD: root123
      volumes:
        - .:/home/project
      espose:
        - 3000