version: smartide/v0.2
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-java-template
    webide-port: 6800
    ports:
      webide-port: 6800
      ssh: 6822
      springboot-application: 8080
    ide-type: jb-projector
    volumes:
      git-config: true
      ssh-key: true
  services:
    smartide-java-template:
      container_name: smartide-java-template
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-jetbrain-idea-c:latest
      restart: always
      environment:
        TZ: Asia/Shanghai
        ROOT_PASSWORD: root123
      volumes:
        - .:/home/project/smartide-java-template
      expose:
        - 8080
      ports:
        - 8080:8080
      networks:
        - boathouse-dev-network

  networks:
    boathouse-dev-network:
      external: true
