version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-java-template
    ports:
      tools-webide-idea: 6800
      tools-ssh: 6822
      apps-springboot-application: 8080
    ide-type: jb-projector
    volumes:
      git-config: true
      ssh-key: true
  services:
    smartide-java-template:
      container_name: smartide-java-template
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-java-v2-jetbrains-idea:2021.2.3-openjdk-11-jdk-2081
      restart: always
      environment:
        TZ: Asia/Shanghai
        ROOT_PASSWORD: root123
      volumes:
        - .:/home/project/smartide-java-template
      expose:
        - 8080
      ports:
        - 6822:22
        - 6800:8887
        - 8080:8080
      networks:
        - boathouse-dev-network

  networks:
    boathouse-dev-network:
      external: true
