
version: "3"
services:
    smartide-java-springboot-idea-template:
      container_name: smartide-java-springboot-idea-template
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-java-v2-jetbrains-idea:latest
      restart: always
      environment:
        TZ: Asia/Shanghai
        ROOT_PASSWORD: root123
      volumes:
        - .:/home/project/smartide-java-template
      expose:
        - 8080
      ports:
        - 6822:22
        - 6800:8887
        - 8080:8080
      networks:
        - smartide-java-network

networks:
    smartide-java-network:
      external: true