---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartide-idea-allinone-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      smartide-allinone.service: smartide-idea-allinone
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        smartide-allinone.service: smartide-idea-allinone
    spec:
      containers:
        - env:
            - name: LOCAL_USER_PASSWORD
              value: root123
          image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-allinone-v2-jetbrains-idea:latest
          imagePullPolicy: Always
          name: smartide-idea-allinone-dev
          ports:
            - containerPort: 8887
            - containerPort: 22
            
          resources:
            requests:
              memory: "2Gi"
              cpu: "2000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: smartide-idea-allinone-service
spec:
  ports:   
    - name: "6800"
      port: 6800
      targetPort: 8887
    - name: "6822"
      port: 6822
      targetPort: 22
  selector:
    smartide-allinone.service: smartide-idea-allinone
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smartide-idea-allinone-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              smartide-idea-allinone/smartide-network: "true"
  podSelector:
    matchLabels:
      smartide-idea-allinone/smartide-network: "true"
