version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-golang
    ports:
      webide: 6800
      ssh: 6822
    ide-type: vscode
    volumes: 
        git-config: true
        ssh-key: true
    command: 
        - go env -w GOPROXY=https://goproxy.cn,direct
    
  services:
    smartide-template-golang:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-go-opvscode:latest
      restart: always
      environment:
        ROOT_PASSWORD: root123
      volumes:
        - .:/home/project
      espose:
        - 3000
