version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-golang
    ports:
      tools-webide-port: 6800
      tools-ssh: 6822
    ide-type: sdk-only
    volumes: 
        git-config: true
        ssh-key: true
    command: 
      - go env -w GOPROXY=https://goproxy.cn,direct
    
  services:
    smartide-template-golang:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-golang-v2:1746
      restart: always
      environment:
        LOCAL_USER_PASSWORD: root123
      ports:
        - 6822:22
        - 6800:3000
      volumes:
        - .:/home/project
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true      
