version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: smartide-vscode-dotnet-dev

    ports:
      tools-webide-vscode: 6800
      tools-ssh: 6822
    ide-type: vscode

    volumes: 
      git-config: true
      ssh-key: true
    command:
      - code --install-extension muhammad-sammy.csharp
      # - code --install-extension MS-CEINTL.vscode-language-pack-zh-hans
      # - dotnet new console


  kube-deploy-files: "vscode-k8s-deployment.yaml" 
  docker-compose-file: "vscode-docker-compose.yaml"