version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-node-webstorm
    ports:
      webide: 6800
      ssh: 6822
      application: 3001
    ide-type: jb-projector
    volumes: 
      git-config: true
      ssh-key: true
      
  services:
    smartide-template-node-webstorm:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-node-v2-jetbrain-webstorm:2020.3.3-2043
      restart: always
      environment:
		    ROOT_PASSWORD: root123
        LOCAL_USER_PASSWORD: root123
      volumes:
        - .:/home/project
      ports:
        - 3001:3001
        - 6822:22
        - 6800:8887
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true