version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-vmlc-vscode-service

    ports:
      tools-ssh: 6822
      tools-webide-vscode: 6800
    ide-type: vscode

    volumes: 
      git-config: true
      ssh-key: true

  kube-deploy-files: "vscode-vmlc-k8s-deployment.yaml" 
  docker-compose-file: "vscode-vmlc-docker-compose.yaml"