
version: "3"
services:
  smartide-dotnet-dev:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-dotnet-v2:latest #=dotnet6 sdk    
    imagePullPolicy: Always
    restart: always
    environment:
      LOCAL_USER_PASSWORD: root123       
    volumes:
    - .:/home/project
    ports:
      - 6822:22
    networks:
      - smartide-network

networks:
  smartide-network:
    external: true