---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartide-pycharm-python-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      smartide-python.service: smartide-pycharm-python
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        smartide-python.service: smartide-pycharm-python
    spec:
      containers:
        - env:
            - name: LOCAL_USER_PASSWORD
              value: root123
          image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-python-v2-jetbrains-pycharm:latest
          imagePullPolicy: Always
          name: smartide-pycharm-python-dev
          ports:
            - containerPort: 8887
            - containerPort: 22
            
          resources:
            requests:
              memory: "2Gi"
              cpu: "2000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: smartide-pycharm-python-service
spec:
  ports:   
    - name: "6800"
      port: 6800
      targetPort: 8887
    - name: "6822"
      port: 6822
      targetPort: 22
  selector:
    smartide-python.service: smartide-pycharm-python
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smartide-pycharm-python-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              smartide-pycharm-python/smartide-network: "true"
  podSelector:
    matchLabels:
      smartide-pycharm-python/smartide-network: "true"
