version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-base-vmlc
    ports:
      tools-ssh: 6822
    ide-type: sdk-only
    volumes: 
      git-config: true
      ssh-key: true
      
  services:
    smartide-template-base-vmlc:
      image:  registry.cn-hangzhou.aliyuncs.com/smartide/smartide-base-v2-vmlc
      restart: always
      volumes:
        - .:/home/project
      ports:
        - 6822:22
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true