version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-php
    ports:
      tools-ssh: 6822
      apps-apache:  8080
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - sudo apache2ctl -k start
    #  - cd / && ./start-xdebug.sh 9003 openvs
  services:
    smartide-template-php:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-php-v2:2107
      restart: always
      environment:
        ROOT_PASSWORD: root123
        LOCAL_USER_PASSWORD: root123
      ports:
        - 6822:22     
        - 8080:80 #apache2 web server
      volumes:
        - .:/home/project
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true      
