
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartide-php-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      smartide-php.service: smartide-php
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        smartide-php.service: smartide-php
    spec:
      containers:
        - env:
            - name: LOCAL_USER_PASSWORD
              value: root123           
          image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-php-v2:latest
          imagePullPolicy: Always
          name: smartide-php-dev
          ports:
            - containerPort: 22
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: smartide-php-service
spec:
  ports:    
    - name: "6822"
      port: 6822
      targetPort: 22
  selector:
    smartide-php.service: smartide-php
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smartide-php-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              smartide-php/smartide-network: "true"
  podSelector:
    matchLabels:
      smartide-php/smartide-network: "true"
