version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-php
    ports:
      tools-webide-port: 6800
      tools-ssh: 6822
    ide-type: vscode
    volumes:
      git-config: true
      ssh-key: true
    command:
      - git config core.filemode false
      - chmod -R 777 /home/project
      - apache2ctl -k start
      - cd / && ./start-xdebug.sh 9003 openvs
  services:
    smartide-template-php:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-opvscode-php:latest
      restart: always
      environment:
        ROOT_PASSWORD: root123
      volumes:
        - .:/home/project
      expose:
        - 3000
      ports:
        - 8080:80
      networks:
        - smartide-network
    itop-db:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: leansoft
      restart: always
      volumes:
        - ./mysql/conf/my.cnf:/etc/my.cnf
        - ../mysql-db:/var/lib/mysql
      ports:
        - 3306:3306
      networks:
        - smartide-network
  networks:
    smartide-network:
      external: true