version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-node-express
    ports:
      webide: 6800
      ssh: 6822
    ide-type: vscode
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm install
      - npm start
  services:
    smartide-template-node-express:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-slim:latest
      restart: always
      environment:
        ROOT_PASSWORD: root123
      volumes:
        - .:/home/project
      expose:
        - 3000
      ports:
        - 3001:3001
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true