version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-node-webstorm
    ports:
      tools-webide-phpstorm: 6800
      tools-ssh: 6822
      apps-application: 8080
    ide-type: jb-projector
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - sudo apache2ctl -k start
    #  - cd / && ./start-xdebug.sh 9003 openvs
      
  services:
    smartide-template-node-webstorm:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-php-v2-jetbrains-phpstorm:2021.3.2-php7.4-2109
      restart: always
      environment:
        ROOT_PASSWORD: root123
        LOCAL_USER_PASSWORD: root123
      volumes:
        - .:/home/project
      ports:
        - 6822:22
        - 6800:8887
        - 8080:80 #apache2 web server
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true