version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: smartide-rider-vmlc-dotnet-dev

    ports:
      tools-webide-rider: 6800
      tools-ssh: 6822
    ide-type: jb-projector

    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config get registry

  kube-deploy-files: "rider-vmlc-k8s-deployment.yaml" 
  docker-compose-file: "rider-vmlc-docker-compose.yaml"