---

apiVersion: v1
kind: Pod
metadata:
  name: smartide-rider-vmlc-dotnet-dev
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
  labels:
    smartide-dotnet.service: smartide-rider-vmlc-dotnet
spec:
  runtimeClassName: sysbox-runc
  containers:
    - env:
        - name: LOCAL_USER_PASSWORD
          value: root123     
      name: smartide-rider-vmlc-dotnet-dev
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-dotnet-v2-jetbrains-rider-vmlc:latest
      command: ["/sbin/init"]
      imagePullPolicy: Always
      ports:
        - containerPort: 22
        - containerPort: 8887
      resources:
        requests:
          memory: "2Gi"
          cpu: "2000m"
        limits:
          memory: "2Gi"
          cpu: "2000m"


---

apiVersion: v1
kind: Service
metadata:
  name: smartide-rider-vmlc-dotnet-service
spec:
  ports:   
    - name: "6800"
      port: 6800
      targetPort: 8887
    - name: "6822"
      port: 6822
      targetPort: 22
  selector:
    smartide-dotnet.service: smartide-rider-vmlc-dotnet
status:
  loadBalancer: {}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smartide-rider-vmlc-dotnet-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              smartide-rider-vmlc-dotnet/smartide-network: "true"
  podSelector:
    matchLabels:
      smartide-rider-vmlc-dotnet/smartide-network: "true"