version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: smartide-vmlc-vscode-php-dev

    ports:
      tools-webide-vscode: 6800
      tools-ssh: 6822
    ide-type: vscode

    volumes: 
      git-config: true
      ssh-key: true
    command:
      - sudo apache2ctl -k start


  kube-deploy-files: "vscode-vmlc-k8s-deployment.yaml" 
  docker-compose-file: "vscode-vmlc-docker-compose.yaml"