version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: ruoyi-dev

    ports:
      tools-webide-idea: 6800
      tools-ssh: 6822
      tools-phpmyadmin: 8090
      tools-nacos: 8848
      tools-sonar: 9000
      apps-ruoyi-ui: 8000
      apps-ruoyi-admin: 8080
    ide-type: jb-projector

    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config get registry

  # kube-deploy-files: "idea-k8s-deployment.yaml" 
  docker-compose-file: "idea-docker-compose.yaml"