version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: smartide-clion-vmlc-cpp-dev

    ports:
      tools-webide-clion: 6800
      tools-ssh: 6822
    ide-type: jb-projector

    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config get registry

  kube-deploy-files: "clion-vmlc-k8s-deployment.yaml" 
  docker-compose-file: "clion-vmlc-docker-compose.yaml"