version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: smartide-webstorm-node-dev

    ports:
      tools-webide-vscode: 6800
      tools-ssh: 6822
    ide-type: jb-projector

    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config get registry
    #  - npm install -g express-generator
    #  - express --view=pug myapp
    #  - npm config set registry https://registry.npmmirror.com
    #  - npm install
    #  - npm start

  kube-deploy-files: "webstorm-k8s-deployment.yaml" 
  docker-compose-file: "webstorm-docker-compose.yaml"