version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: smartide-pycharm-vmlc-python-dev

    ports:
      tools-webide-pycharm: 6800
      tools-ssh: 6822
    ide-type: jb-projector

    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config get registry

  kube-deploy-files: "pycharm-vmlc-k8s-deployment.yaml" 
  docker-compose-file: "pycharm-vmlc-docker-compose.yaml"