version: smartide/v0.1
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-java-idea
    ports:
      webide: 6800
      ssh: 6822
      application: 3001
    ide-type: jb-projector
    volumes: 
        git-config: true
        ssh-key: true
  services:
    smartide-template-java-idea:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-dotnet-v2-jetbrains-rider:2021.3.3-2142
      #image: smartide/smartide-java-v2-jetbrains-idea:2021.2.3-2081
      restart: always
      environment:
        ROOT_PASSWORD: root123
        LOCAL_USER_PASSWORD: root123
      ports:
        - 3001:3001
        - 6822:22
        - 6800:8887
      volumes:
        - .:/home/project
      networks:
        - smartide-network  
  networks:
    smartide-network:
      external: true      
