version: smartide/v0.3
orchestrator:
  type: allinone
  version: 3
workspace:
  dev-container:
    service-name: smartide-opensumi-node-dev

    ports:
      tools-webide-opensumi: 6800
      tools-ssh: 6822
    ide-type: opensumi

    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config set registry https://registry.npmmirror.com
      - npm install

  kube-deploy-files: "opensumi-k8s-deployment.yaml" 
  docker-compose-file: "opensumi-docker-compose.yaml"