version: smartide/v0.3
orchestrator:
  type: docker-compose
  version: 3
workspace:
  dev-container:
    service-name: smartide-template-node-opensumi
    ports: # 申明端口
      tools-webide-opensumi: 6800
      tools-ssh: 6822
      apps-application: 3001

    ide-type: opensumi
    volumes: 
      git-config: true
      ssh-key: true
    command:
      - npm config set registry https://registry.npmmirror.com
      - npm install
  services:
    smartide-template-node-opensumi:
      image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-node-v2-opensumi:latest
      restart: always
      environment:
        ROOT_PASSWORD: root123
        LOCAL_USER_PASSWORD: root123       
      volumes:
      - .:/home/project
      ports:
        - 3001:3001
        - 6822:22
        - 6800:8000
      networks:
        - smartide-network

  networks:
    smartide-network:
      external: true