
version: "3"
services:
  smartide-opensumi-node-dev:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-node-v2-opensumi:latest
    hostname: dev-container
    restart: always
    environment:
      LOCAL_USER_PASSWORD: root123       
    volumes:
      - .:/home/project
    ports:
      - 6822:22
      - 6800:8000
    networks:
      - smartide-network  

networks:
  smartide-network:
    external: true